version: "3.5"
services:
  cql-proxy:
    container_name: cqlproxy
    image: datastax/cql-proxy:v${CQL_PROXY_VERSION}
    healthcheck:
      test: 'printf "GET /readiness HTTP/1.0\r\nHost: localhost\r\n\r\n" | nc localhost 8000 | grep "200 OK"'
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - temporal-network
    ports:
      - 9042:9042
      - 8000:8000
    environment:
      - ASTRA_TOKEN=${ASTRA_TOKEN}
      - ASTRA_DATABASE_ID=${ASTRA_DATABASE_ID}
      - HEALTH_CHECK=true
  temporal:
    container_name: temporal
    depends_on:
      cql-proxy:
        condition: service_healthy # Wait for readiness check on cql-proxy
    environment:
      - CASSANDRA_SEEDS=cqlproxy
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - SKIP_SCHEMA_SETUP=true
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
    ports:
      - 8080:8080
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
